class TokenValidationError(Exception):
    """Исключение вызывается при проблемах токена."""

    pass


class ResponseError(Exception):
    """Исключение вызывается при проблемах c ответом API."""

    pass
